config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                       Controller#Action
#                 dashboard GET    /dashboard(.:format)              reports#index
#                     bills GET    /bills(.:format)                  bills#index
#                           POST   /bills(.:format)                  bills#create
#                  new_bill GET    /bills/new(.:format)              bills#new
#                 edit_bill GET    /bills/:id/edit(.:format)         bills#edit
#                      bill PATCH  /bills/:id(.:format)              bills#update
#                           PUT    /bills/:id(.:format)              bills#update
#                    orders GET    /orders(.:format)                 orders#index
#                           POST   /orders(.:format)                 orders#create
#                 new_order GET    /orders/new(.:format)             orders#new
#                 companies GET    /companies(.:format)              companies#index
#                           POST   /companies(.:format)              companies#create
#               new_company GET    /companies/new(.:format)          companies#new
#              edit_company GET    /companies/:id/edit(.:format)     companies#edit
#                   company GET    /companies/:id(.:format)          companies#show
#                           PATCH  /companies/:id(.:format)          companies#update
#                           PUT    /companies/:id(.:format)          companies#update
#                  products GET    /products(.:format)               products#index
#                           POST   /products(.:format)               products#create
#               new_product GET    /products/new(.:format)           products#new
#              edit_product GET    /products/:id/edit(.:format)      products#edit
#                   product GET    /products/:id(.:format)           products#show
#                           PATCH  /products/:id(.:format)           products#update
#                           PUT    /products/:id(.:format)           products#update
#         new_admin_session GET    /admins/sign_in(.:format)         devise/sessions#new
#             admin_session POST   /admins/sign_in(.:format)         devise/sessions#create
#     destroy_admin_session DELETE /admins/sign_out(.:format)        devise/sessions#destroy
#            admin_password POST   /admins/password(.:format)        devise/passwords#create
#        new_admin_password GET    /admins/password/new(.:format)    devise/passwords#new
#       edit_admin_password GET    /admins/password/edit(.:format)   devise/passwords#edit
#                           PATCH  /admins/password(.:format)        devise/passwords#update
#                           PUT    /admins/password(.:format)        devise/passwords#update
# cancel_admin_registration GET    /admins/cancel(.:format)          devise/registrations#cancel
#        admin_registration POST   /admins(.:format)                 devise/registrations#create
#    new_admin_registration GET    /admins/sign_up(.:format)         devise/registrations#new
#   edit_admin_registration GET    /admins/edit(.:format)            devise/registrations#edit
#                           PATCH  /admins(.:format)                 devise/registrations#update
#                           PUT    /admins(.:format)                 devise/registrations#update
#                           DELETE /admins(.:format)                 devise/registrations#destroy
#              admin_unlock POST   /admins/unlock(.:format)          devise/unlocks#create
#          new_admin_unlock GET    /admins/unlock/new(.:format)      devise/unlocks#new
#                           GET    /admins/unlock(.:format)          devise/unlocks#show
#          new_user_session GET    /users/sign_in(.:format)          devise/sessions#new
#              user_session POST   /users/sign_in(.:format)          devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)         devise/sessions#destroy
#             user_password POST   /users/password(.:format)         devise/passwords#create
#         new_user_password GET    /users/password/new(.:format)     devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)    devise/passwords#edit
#                           PATCH  /users/password(.:format)         devise/passwords#update
#                           PUT    /users/password(.:format)         devise/passwords#update
#  cancel_user_registration GET    /users/cancel(.:format)           devise/registrations#cancel
#         user_registration POST   /users(.:format)                  devise/registrations#create
#     new_user_registration GET    /users/sign_up(.:format)          devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)             devise/registrations#edit
#                           PATCH  /users(.:format)                  devise/registrations#update
#                           PUT    /users(.:format)                  devise/registrations#update
#                           DELETE /users(.:format)                  devise/registrations#destroy
#         user_confirmation POST   /users/confirmation(.:format)     devise/confirmations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format) devise/confirmations#new
#                           GET    /users/confirmation(.:format)     devise/confirmations#show
#               user_unlock POST   /users/unlock(.:format)           devise/unlocks#create
#           new_user_unlock GET    /users/unlock/new(.:format)       devise/unlocks#new
#                           GET    /users/unlock(.:format)           devise/unlocks#show
#                      root GET    /                                 redirect(301, users/sign_in)
#

Rails.application.routes.draw do

  get '/dashboard', to: 'dashboards#index', as: 'dashboard'

  resources :bills, only: [:index, :new, :create, :edit, :update]
  resources :orders, only: [:index, :new, :create]
  resources :companies, except: :destroy
  resources :products, except: :destroy

  devise_for :users
  devise_for :admins

  root to: redirect('users/sign_in')
end

app/models/bill.rb
# == Schema Information
#
# Table name: bills
#
#  id          :integer          not null, primary key
#  company_id  :integer          not null
#  amount      :decimal(12, 2)   not null
#  description :text
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_bills_on_company_id  (company_id)
#

class Bill < ActiveRecord::Base
  auto_strip_attributes :title, :description, squish: true

  validates :company, presence: true
  validates_associated :company
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :company

  def self.total_amount company
    bills = Bill.where(company: company)
    bills.sum("amount")
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :create_new_form, only: [:new, :create]
  before_action :create_edit_form, only: [:edit, :update]

  # GET /bills
  # GET /bills.json
  def index
    @bills = policy_scope(Bill)
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill_form.submit(bill_params)

    respond_to do |format|
      if @bill_form.save
        format.html { redirect_to bills_path, notice: "Bill: #{@bill_form.title} was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    @bill_form.submit(bill_params)

    respond_to do |format|
      if @bill_form.save
        format.html { redirect_to bills_path, notice: "Bill: #{@bill_form.title} was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
      authorize @bill
    end

    def create_new_form
      bill = Bill.new
      authorize bill
      @bill_form = BillForm.new(bill)
    end

    def create_edit_form
      @bill_form = BillForm.new(@bill)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(*policy(@bill || Bill).permitted_attributes)
    end
  end

app/views/bills/_bill.html.erb
<tr>
  <% if admin_signed_in? %>
    <td><%= link_to bill.company.name, company_path(bill.company) %></td>
  <% end %>

  <td><%= bill.title %></td>
  <td><%= number_to_currency bill.amount %></td>
  <td><%= bill.description %></td>
  <% if policy(bill).edit? %>
    <td><%= link_to "Edit", edit_bill_path(bill), class: "btn btn-primary text-center" %></td>
  <% end %>
</tr>

app/views/bills/_form.html.erb
<%= simple_form_for @bill_form, wrapper: :horizontal_form, :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.association :company, prompt: "Choose a Company" %>

  <%= f.input :title, hint: "Paid User Reviews / Poster Design / Cutsom Title" %>

  <%= f.input :amount, wrapper: :horizontal_input_group do %>
    <span class="input-group-addon">&yen;</span>
    <%= f.input_field :amount, as: :integer, min: 0, step: 0.01, placeholder: "0.00", class: "form-control" %>
  <% end %>

  <%= f.input :description, as: :text, input_html: {rows: 5}, placeholder: "Optional" %>

  <%= f.button :button, class: "btn btn-lg btn-block btn-effect-ripple btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Just a moment..."} %>
<% end %>

app/views/bills/edit.html.erb
<%= content_for :title, 'Edit Bill' %>

<div class="row">
<div class="col-md-8  col-md-offset-2">
<div class="block">
  <div class="block-title">
    <h2>Edit Bill</h2>
  </div>
  <%= render 'form' %>
</div>
</div>

app/views/bills/index.html.erb
<%= content_for :title, 'Bills' %>

<!-- Partial Responsive Block -->
<div class="block">
  <!-- Partial Responsive Title -->
  <div class="block-title">
    <div class="block-options pull-right">
      <% if admin_signed_in? %>
        <%= link_to 'Add New', new_bill_path, class: "btn btn-primary" %>
      <% end %>
    </div>
    <h2>Bills</h2>
  </div>
  <!-- END Partial Responsive Title -->

  <!-- Partial Responsive Content -->
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-vcenter">
      <thead>
        <tr>
          <% if admin_signed_in? %>
            <th>Company Name</th>
          <% end %>
          <th>Title</th>
          <th>Amount</th>
          <th>Description</th>
          <% if policy(Bill).edit? %>
            <th>Action</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <%= render @bills %>
      </tbody>
    </table>
  </div>
  <!-- END Partial Responsive Content -->
</div>
<!-- END Partial Responsive Block -->

app/views/bills/new.html.erb
<%= content_for :title, 'Add New Bill' %>

<div class="row">
<div class="col-md-8  col-md-offset-2">
<div class="block">
  <div class="block-title">
    <h2>Add New Bill</h2>
  </div>
  <%= render 'form' %>
</div>
</div>