config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                       Controller#Action
#                 dashboard GET    /dashboard(.:format)              reports#index
#                     bills GET    /bills(.:format)                  bills#index
#                           POST   /bills(.:format)                  bills#create
#                  new_bill GET    /bills/new(.:format)              bills#new
#                 edit_bill GET    /bills/:id/edit(.:format)         bills#edit
#                      bill PATCH  /bills/:id(.:format)              bills#update
#                           PUT    /bills/:id(.:format)              bills#update
#                    orders GET    /orders(.:format)                 orders#index
#                           POST   /orders(.:format)                 orders#create
#                 new_order GET    /orders/new(.:format)             orders#new
#                 companies GET    /companies(.:format)              companies#index
#                           POST   /companies(.:format)              companies#create
#               new_company GET    /companies/new(.:format)          companies#new
#              edit_company GET    /companies/:id/edit(.:format)     companies#edit
#                   company GET    /companies/:id(.:format)          companies#show
#                           PATCH  /companies/:id(.:format)          companies#update
#                           PUT    /companies/:id(.:format)          companies#update
#                  products GET    /products(.:format)               products#index
#                           POST   /products(.:format)               products#create
#               new_product GET    /products/new(.:format)           products#new
#              edit_product GET    /products/:id/edit(.:format)      products#edit
#                   product GET    /products/:id(.:format)           products#show
#                           PATCH  /products/:id(.:format)           products#update
#                           PUT    /products/:id(.:format)           products#update
#         new_admin_session GET    /admins/sign_in(.:format)         devise/sessions#new
#             admin_session POST   /admins/sign_in(.:format)         devise/sessions#create
#     destroy_admin_session DELETE /admins/sign_out(.:format)        devise/sessions#destroy
#            admin_password POST   /admins/password(.:format)        devise/passwords#create
#        new_admin_password GET    /admins/password/new(.:format)    devise/passwords#new
#       edit_admin_password GET    /admins/password/edit(.:format)   devise/passwords#edit
#                           PATCH  /admins/password(.:format)        devise/passwords#update
#                           PUT    /admins/password(.:format)        devise/passwords#update
# cancel_admin_registration GET    /admins/cancel(.:format)          devise/registrations#cancel
#        admin_registration POST   /admins(.:format)                 devise/registrations#create
#    new_admin_registration GET    /admins/sign_up(.:format)         devise/registrations#new
#   edit_admin_registration GET    /admins/edit(.:format)            devise/registrations#edit
#                           PATCH  /admins(.:format)                 devise/registrations#update
#                           PUT    /admins(.:format)                 devise/registrations#update
#                           DELETE /admins(.:format)                 devise/registrations#destroy
#              admin_unlock POST   /admins/unlock(.:format)          devise/unlocks#create
#          new_admin_unlock GET    /admins/unlock/new(.:format)      devise/unlocks#new
#                           GET    /admins/unlock(.:format)          devise/unlocks#show
#          new_user_session GET    /users/sign_in(.:format)          devise/sessions#new
#              user_session POST   /users/sign_in(.:format)          devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)         devise/sessions#destroy
#             user_password POST   /users/password(.:format)         devise/passwords#create
#         new_user_password GET    /users/password/new(.:format)     devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)    devise/passwords#edit
#                           PATCH  /users/password(.:format)         devise/passwords#update
#                           PUT    /users/password(.:format)         devise/passwords#update
#  cancel_user_registration GET    /users/cancel(.:format)           devise/registrations#cancel
#         user_registration POST   /users(.:format)                  devise/registrations#create
#     new_user_registration GET    /users/sign_up(.:format)          devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)             devise/registrations#edit
#                           PATCH  /users(.:format)                  devise/registrations#update
#                           PUT    /users(.:format)                  devise/registrations#update
#                           DELETE /users(.:format)                  devise/registrations#destroy
#         user_confirmation POST   /users/confirmation(.:format)     devise/confirmations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format) devise/confirmations#new
#                           GET    /users/confirmation(.:format)     devise/confirmations#show
#               user_unlock POST   /users/unlock(.:format)           devise/unlocks#create
#           new_user_unlock GET    /users/unlock/new(.:format)       devise/unlocks#new
#                           GET    /users/unlock(.:format)           devise/unlocks#show
#                      root GET    /                                 redirect(301, users/sign_in)
#

Rails.application.routes.draw do

  get '/dashboard', to: 'dashboards#index', as: 'dashboard'

  resources :bills, only: [:index, :new, :create, :edit, :update]
  resources :orders, only: [:index, :new, :create]
  resources :companies, except: :destroy
  resources :products, except: :destroy

  devise_for :users
  devise_for :admins

  root to: redirect('users/sign_in')
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                      :integer          not null, primary key
#  name                    :string           not null
#  email_host              :string           not null
#  inventory_contact_email :string           not null
#  commission_rate         :integer          default(10), not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Company < ActiveRecord::Base
  before_save :downcase_attributes
  auto_strip_attributes :name, squish: true

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email_host, presence: true, uniqueness: { case_sensitive: false }, root_domain: true
  validates :inventory_contact_email, presence: true, email: true
  validates :commission_rate, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  has_many :users
  has_many :bills
  has_many :products
  has_many :variants, through: :products
  has_many :orders, through: :variants

  private
  def downcase_attributes
    self.email_host.downcase! unless self.email_host.blank?
    self.inventory_contact_email.downcase! unless self.inventory_contact_email.blank?
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :create_new_form, only: [:new, :create]
  before_action :create_edit_form, only: [:edit, :update]

  # GET /companies
  # GET /companies.json
  def index
    @companies = policy_scope(Company)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company_form.submit(company_params)

    respond_to do |format|
      if @company_form.save
        format.html { redirect_to @company_form, notice: "Company: #{@company_form.name} was successfully created." }
      else
        format.html { render :new, notice: "Opss.. Something went wrong" }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company_form.submit(company_params)

    respond_to do |format|
      if @company_form.save
        format.html { redirect_to @company_form, notice: "Company: #{@company_form.name} was successfully updated." }
      else
        format.html { render :edit, notice: "Opss.. Something went wrong" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
      authorize @company
    end

    def create_new_form
      company = Company.new
      authorize company
      @company_form = CompanyForm.new(company)
    end

    def create_edit_form
      @company_form = CompanyForm.new(@company)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(*policy(@company || Company).permitted_attributes)
    end
  end

app/views/companies/_company.html.erb
<tr>
  <td><%= link_to company.name, company %></td>
  <td><%= company.email_host %></td>
  <td><%= company.commission_rate %> %</td>
  <td><%= mail_to company.inventory_contact_email %></td>
  <td>
    <% if policy(company).edit? %>
      <%= link_to 'Edit', edit_company_path(company), class: "btn btn-primary" %>
    <% end %>
  </td>
</tr>

app/views/companies/_form.html.erb
<%= simple_form_for @company_form, wrapper: :horizontal_form, :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :name, label: "Company name", disabled: !admin_signed_in? %>

  <%= f.input :email_host, wrapper: :horizontal_input_group, hint: "Users registered with this email host will be added to your company" do %>
    <span class="input-group-addon">username@</span>
    <%= f.input_field :email_host, as: :string, class: "form-control", disabled: !admin_signed_in?  %>
  <% end %>

  <%= f.input :commission_rate, wrapper: :horizontal_input_group, hint: "integer between 0 and 100" do %>
    <%= f.input_field :commission_rate, as: :integer, min: 0, max: 100, class: "form-control", disabled: !admin_signed_in?  %>
    <span class="input-group-addon">%</span>
  <% end %>

  <%= f.input :inventory_contact_email, hint: "Out of stock and low stock alerts will be sent to this email" %>

  <%= f.button :button, class: "btn btn-lg btn-block btn-effect-ripple btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Just a moment..."} %>
<% end %>

app/views/companies/edit.html.erb
<%= content_for :title, 'Edit Company Settings' %>

<div class="row">
<div class="col-md-8  col-md-offset-2">
<div class="block">
  <div class="block-title">
    <h2>Edit Company Settings</h2>
  </div>
  <%= render 'form' %>
</div>
</div>

app/views/companies/index.html.erb
<%= content_for :title, 'Companies' %>

  <!-- Partial Responsive Block -->
  <div class="block">
    <!-- Partial Responsive Title -->
    <div class="block-title">
      <div class="block-options pull-right">
        <% if policy(Company).create? %>
          <%= link_to 'Add New', new_company_path, class: "btn btn-primary" %>
        <% end %>
      </div>
      <h2>Companies</h2>
    </div>
    <!-- END Partial Responsive Title -->

    <!-- Partial Responsive Content -->
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-vcenter">
      <thead>
        <tr>
          <th>Company Name</th>
          <th>Email Host</th>
          <th>Commission Rate</th>
          <th>Inventory Contact Email</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <%= render @companies %>
      </tbody>
    </table>
    </div>
    <!-- END Partial Responsive Content -->
  </div>
  <!-- END Partial Responsive Block -->

app/views/companies/new.html.erb
<%= content_for :title, 'Add New Company' %>

<div class="row">
<div class="col-md-8  col-md-offset-2">
<div class="block">
  <div class="block-title">
    <h2>Add New Company</h2>
  </div>
  <%= render 'form' %>
</div>
</div>

app/views/companies/show.html.erb
<%= content_for :title, 'Company Infomation' %>

<div class="col-md-8  col-md-offset-2">
  <!-- Partial Responsive Block -->
  <div class="block">
    <!-- Partial Responsive Title -->
    <div class="block-title">
      <div class="block-options pull-right">
        <% if policy(Company).create? %>
          <%= link_to 'Add New', new_company_path, class: "btn btn-primary" %>
        <% end %>
        <% if policy(@company).edit? %>
          <%= link_to 'Edit', edit_company_path(@company), class: "btn btn-primary" %>
        <% end %>
      </div>
      <h2><%= @company.name %></h2>
    </div>
    <!-- END Partial Responsive Title -->

    <!-- Partial Responsive Content -->
    <div class="table-responsive">
      <table class="table table-striped table-borderless table-vcenter">
        <tbody>
          <tr>
            <td><strong>Company Name</strong></td>
            <td><%= @company.name %></td>
          </tr>
          <tr>
            <td><strong>Email Host</strong></td>
            <td><%= @company.email_host %></td>
          </tr>
          <tr>
            <td><strong>Commission Rate</strong></td>
            <td><%= @company.commission_rate %> %</td>
          </tr>
          <tr>
            <td><strong>Inventory Contact Email</strong></td>
            <td><%= mail_to @company.inventory_contact_email %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- END Partial Responsive Content -->
  </div>
  <!-- END Partial Responsive Block -->
</div>