config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                       Controller#Action
#                 dashboard GET    /dashboard(.:format)              reports#index
#                     bills GET    /bills(.:format)                  bills#index
#                           POST   /bills(.:format)                  bills#create
#                  new_bill GET    /bills/new(.:format)              bills#new
#                 edit_bill GET    /bills/:id/edit(.:format)         bills#edit
#                      bill PATCH  /bills/:id(.:format)              bills#update
#                           PUT    /bills/:id(.:format)              bills#update
#                    orders GET    /orders(.:format)                 orders#index
#                           POST   /orders(.:format)                 orders#create
#                 new_order GET    /orders/new(.:format)             orders#new
#                 companies GET    /companies(.:format)              companies#index
#                           POST   /companies(.:format)              companies#create
#               new_company GET    /companies/new(.:format)          companies#new
#              edit_company GET    /companies/:id/edit(.:format)     companies#edit
#                   company GET    /companies/:id(.:format)          companies#show
#                           PATCH  /companies/:id(.:format)          companies#update
#                           PUT    /companies/:id(.:format)          companies#update
#                  products GET    /products(.:format)               products#index
#                           POST   /products(.:format)               products#create
#               new_product GET    /products/new(.:format)           products#new
#              edit_product GET    /products/:id/edit(.:format)      products#edit
#                   product GET    /products/:id(.:format)           products#show
#                           PATCH  /products/:id(.:format)           products#update
#                           PUT    /products/:id(.:format)           products#update
#         new_admin_session GET    /admins/sign_in(.:format)         devise/sessions#new
#             admin_session POST   /admins/sign_in(.:format)         devise/sessions#create
#     destroy_admin_session DELETE /admins/sign_out(.:format)        devise/sessions#destroy
#            admin_password POST   /admins/password(.:format)        devise/passwords#create
#        new_admin_password GET    /admins/password/new(.:format)    devise/passwords#new
#       edit_admin_password GET    /admins/password/edit(.:format)   devise/passwords#edit
#                           PATCH  /admins/password(.:format)        devise/passwords#update
#                           PUT    /admins/password(.:format)        devise/passwords#update
# cancel_admin_registration GET    /admins/cancel(.:format)          devise/registrations#cancel
#        admin_registration POST   /admins(.:format)                 devise/registrations#create
#    new_admin_registration GET    /admins/sign_up(.:format)         devise/registrations#new
#   edit_admin_registration GET    /admins/edit(.:format)            devise/registrations#edit
#                           PATCH  /admins(.:format)                 devise/registrations#update
#                           PUT    /admins(.:format)                 devise/registrations#update
#                           DELETE /admins(.:format)                 devise/registrations#destroy
#              admin_unlock POST   /admins/unlock(.:format)          devise/unlocks#create
#          new_admin_unlock GET    /admins/unlock/new(.:format)      devise/unlocks#new
#                           GET    /admins/unlock(.:format)          devise/unlocks#show
#          new_user_session GET    /users/sign_in(.:format)          devise/sessions#new
#              user_session POST   /users/sign_in(.:format)          devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)         devise/sessions#destroy
#             user_password POST   /users/password(.:format)         devise/passwords#create
#         new_user_password GET    /users/password/new(.:format)     devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)    devise/passwords#edit
#                           PATCH  /users/password(.:format)         devise/passwords#update
#                           PUT    /users/password(.:format)         devise/passwords#update
#  cancel_user_registration GET    /users/cancel(.:format)           devise/registrations#cancel
#         user_registration POST   /users(.:format)                  devise/registrations#create
#     new_user_registration GET    /users/sign_up(.:format)          devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)             devise/registrations#edit
#                           PATCH  /users(.:format)                  devise/registrations#update
#                           PUT    /users(.:format)                  devise/registrations#update
#                           DELETE /users(.:format)                  devise/registrations#destroy
#         user_confirmation POST   /users/confirmation(.:format)     devise/confirmations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format) devise/confirmations#new
#                           GET    /users/confirmation(.:format)     devise/confirmations#show
#               user_unlock POST   /users/unlock(.:format)           devise/unlocks#create
#           new_user_unlock GET    /users/unlock/new(.:format)       devise/unlocks#new
#                           GET    /users/unlock(.:format)           devise/unlocks#show
#                      root GET    /                                 redirect(301, users/sign_in)
#

Rails.application.routes.draw do

  get '/dashboard', to: 'dashboards#index', as: 'dashboard'

  resources :bills, only: [:index, :new, :create, :edit, :update]
  resources :orders, only: [:index, :new, :create]
  resources :companies, except: :destroy
  resources :products, except: :destroy

  devise_for :users
  devise_for :admins

  root to: redirect('users/sign_in')
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  description     :text
#  commission_rate :integer
#  ads_budget      :integer          default(0), not null
#  company_id      :integer          not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_products_on_company_id  (company_id)
#

class Product < ActiveRecord::Base
  auto_strip_attributes :name, :description, squish: true

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :commission_rate, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }, allow_nil: true
  validates :ads_budget, numericality: true, presence: true

  ## TODO
  # validates_associated :company

  belongs_to :company
  has_many :variants
  has_many :orders, through: :variants

  def all_time_sale_unit
    orders.sum("unit")
  end

  def all_time_sale_income
    orders.sum("amount")
  end

  def last_30_days_sale_unit
    os = orders.select { |o| o.created_at > (Time.now-30.days) }
    os.sum(&:unit)
  end

  def last_30_days_sale_income
    os = orders.select { |o| o.created_at > (Time.now-30.days) }
    os.sum(&:amount)
  end

  def last_7_days_sale_unit
    os = orders.select { |o| o.created_at > (Time.now-7.days) }
    os.sum(&:unit)
  end

  def last_7_days_sale_income
    os = orders.select { |o| o.created_at > (Time.now-7.days) }
    os.sum(&:amount)
  end

  private
  def sale_unit
    self.order.where()
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :create_new_form, only: [:new, :create]
  before_action :create_edit_form, only: [:edit, :update]

  # GET /products
  # GET /products.json
  def index
    @products = policy_scope(Product)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product_form.submit(product_params)

    respond_to do |format|
      if @product_form.save
        format.html { redirect_to @product_form, notice: "Product: #{@product_form.name} was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product_form.submit(product_params)

    respond_to do |format|
      if @product_form.save
        format.html { redirect_to @product_form, notice: "Product: #{@product_form.name} was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    name = @product.name
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product: #{name} was successfully destroyed." }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end

  def create_new_form
    if current_company.present?
      product = current_company.products.new
    else
      product = Product.new
    end

    authorize product
    @product_form = ProductForm.new(product)
  end

  def create_edit_form
    @product_form = ProductForm.new(@product)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(*policy(@product || Product).permitted_attributes)
  end
end

app/views/products/_form.html.erb
<%= simple_form_for @product_form, wrapper: :horizontal_form, :html => {:class => 'form-horizontal' } do |f| %>

  <div class="field">
    <%= f.input :name %>
  </div>
  <div class="field">
    <%= f.input :description, as: :text %>
  </div>

  <div class="field">
    <%= f.input :ads_budget, as: :integer %>
  </div>

  <% if admin_signed_in? %>
    <%= f.input :commission_rate %>
  <% end %>

  <%= f.simple_fields_for :variants do |variant_fields| %>
    <%= render "variant_fields", :f => variant_fields %>
  <% end %>

  <div class="links">
    <%= link_to_add_association "Add New Variant", f, :variants, class: "btn btn-effect-ripple btn-success" %>
  </div>
  <div class="actions">
    <%= f.button :submit, class: "btn btn-lg btn-block btn-effect-ripple btn-primary" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= link_to product.name, product %></td>
  <td><%= product.description %></td>
  <td><%= number_to_currency product.ads_budget %></td>
  <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary" %></td>
</tr>

app/views/products/_variant.html.erb
<tr class="info"><td></td><td></td></tr>
<tr>
  <td><strong>Variant Name</strong></td>
  <td><%= variant.name %></td>
</tr>
<tr>
  <td><strong>Your SKU</strong></td>
  <td><%= variant.your_sku %></td>
</tr>
<tr>
  <td><strong>Inventory</strong></td>
  <td><%= variant.inventory %></td>
</tr>
<tr>
  <td><strong>Minimum Price</strong></td>
  <td><%= number_to_currency variant.minimum_price %></td>
</tr>

<% if variant.commission_rate.present? %>
<tr>
  <td><strong>Commission Rate</strong></td>
  <td><%= variant.commission_rate %></td>
</tr>
<% end %>

app/views/products/_variant_fields.html.erb
<br />
<br />

<div class="nested-fields">
  <div class="field">
    <%= f.input :name, label: "Variant Name" %>
  </div>
  <div class="field">
    <%= f.input :your_sku %>
  </div>
  <div class="field">
    <%= f.input :inventory, as: :integer %>
  </div>
  <div class="field">
    <%= f.input :minimum_price, as: :integer %>
  </div>

  <% if admin_signed_in? %>
    <%= f.input :commission_rate %>
    <%= f.input :our_sku %>
  <% end %>

  <%= link_to_remove_association "Delete Variant", f, class: "btn btn-effect-ripple btn-default pull-right" %>
</div>

app/views/products/edit.html.erb
<%= content_for :title, 'Edit Product' %>

<div class="row">
<div class="col-md-8  col-md-offset-2">
<div class="block">
  <div class="block-title">
    <h2>Edit Product</h2>
  </div>
  <%= render 'form' %>
</div>
</div>

app/views/products/index.html.erb
<%= content_for :title, 'Products' %>

<div class="col-md-12">
  <!-- Partial Responsive Block -->
  <div class="block">
    <!-- Partial Responsive Title -->
    <div class="block-title">
      <div class="block-options pull-right">
        <%= link_to 'Add New', new_product_path, class: "btn btn-primary" %>
      </div>
      <h2>Products</h2>
    </div>
    <!-- END Partial Responsive Title -->

    <!-- Partial Responsive Content -->
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-vcenter">
      <thead>
        <tr>
          <th>Product Name</th>
          <th>Description</th>
          <th>Ads Budget</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <%= render @products %>
      </tbody>
    </table>
    </div>
    <!-- END Partial Responsive Content -->
  </div>
  <!-- END Partial Responsive Block -->
</div>

app/views/products/new.html.erb
<%= content_for :title, 'Add New Product' %>

<div class="row">
<div class="col-md-8  col-md-offset-2">
<div class="block">
  <div class="block-title">
    <h2>Add New Product</h2>
  </div>
  <%= render 'form' %>
</div>
</div>

app/views/products/show.html.erb
<%= content_for :title, @product.name %>
<div class="row">

  <div class="col-md-8">
    <!-- Partial Responsive Block -->
    <div class="block">
      <!-- Partial Responsive Title -->
      <div class="block-title">
        <div class="block-options pull-right">
          <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-primary" %>
        </div>
        <h2><%= @product.name %></h2>
      </div>
      <!-- END Partial Responsive Title -->

      <!-- Partial Responsive Content -->

      <table class="table table-striped table-borderless table-vcenter">
        <tbody>
          <tr>
            <td><strong>Product Name</strong></td>
            <td><%= @product.name %></td>
          </tr>
          <tr>
            <td><strong>Description</strong></td>
            <td><%= @product.description %></td>
          </tr>
          <% if @product.commission_rate.present? %>
          <tr>
            <td><strong>Commission Rate</strong></td>
            <td><%= @product.commission_rate %></td>
          </tr>
          <% end %>
          <tr>
            <td><strong>Ads Budget</strong></td>
            <td><%= number_to_currency @product.ads_budget %></td>
          </tr>

          <% @product.variants.each do |variant| %>
          <%= render partial: "variant", object: variant %>
          <% end %>

        </tbody>
      </table>

      <!-- END Partial Responsive Content -->
    </div>
    <!-- END Partial Responsive Block -->

  </div>

  <div class="col-md-4">
    <!-- Partial Responsive Block -->
    <div class="block">
      <!-- Partial Responsive Title -->
      <div class="block-title">
        <div class="block-options pull-right">
          <%= link_to 'Add Budget', edit_product_path(@product), class: "btn btn-primary" %>
        </div>
        <h2>Ads</h2>
      </div>
      <!-- END Partial Responsive Title -->
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-vcenter">
          <tbody>
            <tr>
              <td><strong>Impression</strong></td>
              <td>1398</td>
            </tr>
            <tr>
              <td><strong>Conversion Rate</strong></td>
              <td>12.3%</td>
            </tr>
            <tr>
              <td><strong>Leads (Income)</strong></td>
              <td>$ 1400</td>
            </tr>
            <tr>
              <td><strong>Leads (Sales)</strong></td>
              <td>36</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

    <div class="col-md-4">
    <!-- Partial Responsive Block -->
    <div class="block">
      <!-- Partial Responsive Title -->
      <div class="block-title">
        <div class="block-options pull-right">
        </div>
        <h2>Sales Summary</h2>
      </div>
      <!-- END Partial Responsive Title -->
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-vcenter">
          <tbody>
            <tr>
              <td>Period</td>
              <td>Unit Sold</td>
              <td>Sales</td>
            </tr>
            <tr>
              <td><strong>All Time</strong></td>
              <td><%= @product.all_time_sale_unit %></td>
              <td><%= number_to_currency @product.all_time_sale_income %></td>
            </tr>
            <tr>
              <td><strong>Last 30 Days</strong></td>
              <td><%= @product.last_30_days_sale_unit %></td>
              <td><%= number_to_currency @product.last_30_days_sale_income %></td>
            </tr>
            <tr>
              <td><strong>Last 7 Days</strong></td>
              <td><%= @product.last_7_days_sale_unit %></td>
              <td><%= number_to_currency @product.last_7_days_sale_income %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>