config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                       Controller#Action
#                 dashboard GET    /dashboard(.:format)              reports#index
#                     bills GET    /bills(.:format)                  bills#index
#                           POST   /bills(.:format)                  bills#create
#                  new_bill GET    /bills/new(.:format)              bills#new
#                 edit_bill GET    /bills/:id/edit(.:format)         bills#edit
#                      bill PATCH  /bills/:id(.:format)              bills#update
#                           PUT    /bills/:id(.:format)              bills#update
#                    orders GET    /orders(.:format)                 orders#index
#                           POST   /orders(.:format)                 orders#create
#                 new_order GET    /orders/new(.:format)             orders#new
#                 companies GET    /companies(.:format)              companies#index
#                           POST   /companies(.:format)              companies#create
#               new_company GET    /companies/new(.:format)          companies#new
#              edit_company GET    /companies/:id/edit(.:format)     companies#edit
#                   company GET    /companies/:id(.:format)          companies#show
#                           PATCH  /companies/:id(.:format)          companies#update
#                           PUT    /companies/:id(.:format)          companies#update
#                  products GET    /products(.:format)               products#index
#                           POST   /products(.:format)               products#create
#               new_product GET    /products/new(.:format)           products#new
#              edit_product GET    /products/:id/edit(.:format)      products#edit
#                   product GET    /products/:id(.:format)           products#show
#                           PATCH  /products/:id(.:format)           products#update
#                           PUT    /products/:id(.:format)           products#update
#         new_admin_session GET    /admins/sign_in(.:format)         devise/sessions#new
#             admin_session POST   /admins/sign_in(.:format)         devise/sessions#create
#     destroy_admin_session DELETE /admins/sign_out(.:format)        devise/sessions#destroy
#            admin_password POST   /admins/password(.:format)        devise/passwords#create
#        new_admin_password GET    /admins/password/new(.:format)    devise/passwords#new
#       edit_admin_password GET    /admins/password/edit(.:format)   devise/passwords#edit
#                           PATCH  /admins/password(.:format)        devise/passwords#update
#                           PUT    /admins/password(.:format)        devise/passwords#update
# cancel_admin_registration GET    /admins/cancel(.:format)          devise/registrations#cancel
#        admin_registration POST   /admins(.:format)                 devise/registrations#create
#    new_admin_registration GET    /admins/sign_up(.:format)         devise/registrations#new
#   edit_admin_registration GET    /admins/edit(.:format)            devise/registrations#edit
#                           PATCH  /admins(.:format)                 devise/registrations#update
#                           PUT    /admins(.:format)                 devise/registrations#update
#                           DELETE /admins(.:format)                 devise/registrations#destroy
#              admin_unlock POST   /admins/unlock(.:format)          devise/unlocks#create
#          new_admin_unlock GET    /admins/unlock/new(.:format)      devise/unlocks#new
#                           GET    /admins/unlock(.:format)          devise/unlocks#show
#          new_user_session GET    /users/sign_in(.:format)          devise/sessions#new
#              user_session POST   /users/sign_in(.:format)          devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)         devise/sessions#destroy
#             user_password POST   /users/password(.:format)         devise/passwords#create
#         new_user_password GET    /users/password/new(.:format)     devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)    devise/passwords#edit
#                           PATCH  /users/password(.:format)         devise/passwords#update
#                           PUT    /users/password(.:format)         devise/passwords#update
#  cancel_user_registration GET    /users/cancel(.:format)           devise/registrations#cancel
#         user_registration POST   /users(.:format)                  devise/registrations#create
#     new_user_registration GET    /users/sign_up(.:format)          devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)             devise/registrations#edit
#                           PATCH  /users(.:format)                  devise/registrations#update
#                           PUT    /users(.:format)                  devise/registrations#update
#                           DELETE /users(.:format)                  devise/registrations#destroy
#         user_confirmation POST   /users/confirmation(.:format)     devise/confirmations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format) devise/confirmations#new
#                           GET    /users/confirmation(.:format)     devise/confirmations#show
#               user_unlock POST   /users/unlock(.:format)           devise/unlocks#create
#           new_user_unlock GET    /users/unlock/new(.:format)       devise/unlocks#new
#                           GET    /users/unlock(.:format)           devise/unlocks#show
#                      root GET    /                                 redirect(301, users/sign_in)
#

Rails.application.routes.draw do

  get '/dashboard', to: 'dashboards#index', as: 'dashboard'

  resources :bills, only: [:index, :new, :create, :edit, :update]
  resources :orders, only: [:index, :new, :create]
  resources :companies, except: :destroy
  resources :products, except: :destroy

  devise_for :users
  devise_for :admins

  root to: redirect('users/sign_in')
end

app/views/layouts/_messages.html.erb
<% if ! flash.blank? %>
  <%# Rails flash messages styled for Bootstrap 3.0 %>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
            <% case name %>
          <% when "error", "alert" %>
          <% context = "danger" %>
          <% when "warning" %>
          <% context = "warning" %>
          <% when "success" %>
          <% context = "success" %>
          <% else %>
          <% context = "info" %>
          <% end %>

      <div class="alert alert-<%= context %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Header -->
<header class="navbar navbar-inverse navbar-fixed-top">
  <!-- Left Header Navigation -->
  <ul class="nav navbar-nav-custom">
    <!-- Main Sidebar Toggle Button -->
    <li>
      <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar');
      this.blur();">
      <i class="fa fa-ellipsis-v fa-fw animation-fadeInRight" id="sidebar-toggle-mini"></i>
      <i class="fa fa-bars fa-fw animation-fadeInRight" id="sidebar-toggle-full"></i>
    </a>
  </li>
  <!-- END Main Sidebar Toggle Button -->

  <!-- Header Link -->
</ul>
<!-- END Left Header Navigation -->

<!-- Right Header Navigation -->
<ul class="nav navbar-nav-custom pull-right">
  <% if user_signed_in? %>
      <li class="hidden-xs animation-fadeInQuick">
      <li><%= link_to current_company.name, edit_company_path(current_company) %></li>
    </li>
    <li class="hidden-xs animation-fadeInQuick">
      <li><%= link_to current_user.email, edit_user_registration_path %></li>
    </li>
    <li class="hidden-xs animation-fadeInQuick">
      <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
    </li>
    <% elsif admin_signed_in? %>
    <li class="hidden-xs animation-fadeInQuick">
      <li><%= link_to current_admin.email, edit_admin_registration_path %></li>
    </li>
    <li class="hidden-xs animation-fadeInQuick">
      <li><%= link_to 'Sign out', destroy_admin_session_path, :method=>'delete' %></li>
    </li>
  <% else %>
    <li class="hidden-xs animation-fadeInQuick">
      <li><%= link_to 'Login', new_user_session_path %></li>
    </li>
    <li class="hidden-xs animation-fadeInQuick">
      <li><%= link_to 'Sign up', new_user_registration_path %></li>
    </li>
  <% end %>
</ul>
<!-- END Right Header Navigation -->
<!-- END Header Link -->
</header>
<!-- END Header -->

app/views/layouts/_page_header.html.erb
<% if content_for?(:title) %>
<!-- Page Header -->
<div class="content-header">
  <div class="row">
    <div class="col-sm-6">
      <div class="header-section">
        <h1><%= yield(:title) %><h1>
      </div>
    </div>
    <div class="col-sm-6 hidden-xs">
      <div class="header-section">
        <% if  content_for?(:breadcrumb) %>
        <ul class="breadcrumb breadcrumb-top">
          <%= yield(:breadcrumb) %>
        </ul>%
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- END Page Header -->
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- Main Sidebar -->
<div id="sidebar">
  <!-- Sidebar Brand -->
  <div id="sidebar-brand" class="themed-background">
    <a href="index.html" class="sidebar-title">
      <i class="fa fa-cube"></i> <span class="sidebar-nav-mini-hide">Glamor<strong>Trade</strong></span>
    </a>
  </div>
  <!-- END Sidebar Brand -->

  <!-- Wrapper for scrolling functionality -->
  <div id="sidebar-scroll">
    <!-- Sidebar Content -->
    <div class="sidebar-content">
      <!-- Sidebar Navigation -->
      <ul class="sidebar-nav">

        <% if admin_signed_in? %>
          <%= link_to "<i class='gi gi-home sidebar-nav-icon'></i><span class='sidebar-nav-mini-hide'>Companies</span>", companies_path %>
        </li>
        <% else %>
        <li>
          <%= link_to "<i class='gi gi-compass sidebar-nav-icon'></i><span class='sidebar-nav-mini-hide'>Dashboard</span>", dashboard_path %>
        </li>
        <li class="sidebar-separator">
          <i class="fa fa-ellipsis-h"></i>
        </li>
        <% end %>

        <li>
          <%= link_to  "<i class='gi gi-gift  sidebar-nav-icon'></i></i><span class='sidebar-nav-mini-hide'>Products</span>", products_path %>
        </li>

        <li>
          <%= link_to  "<i class='gi gi-briefcase sidebar-nav-icon'></i><span class='sidebar-nav-mini-hide'>Bills</span>", bills_path %>
        </li>

        <li>
          <%= link_to  "<i class='fa fa-jpy sidebar-nav-icon'></i><span class='sidebar-nav-mini-hide'>Sales</span>", orders_path %>
        </li>

      </ul>
      <!-- END Sidebar Navigation -->
    </div>
    <!-- END Sidebar Content -->
  </div>
  <!-- END Wrapper for scrolling functionality -->

  <!-- Sidebar Extra Info -->
  <div id="sidebar-extra-info" class="sidebar-content sidebar-nav-mini-hide">
    <div class="text-center">
      <small><span id="year-copy"></span> &copy; <%= link_to "GlamorTrade", root_path %> </small>
    </div>
  </div>
  <!-- END Sidebar Extra Info -->
</div>
<!-- END Main Sidebar -->

app/views/layouts/application.html.erb
</html><!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title><%= content_for?(:title) ? yield(:title) + " | GlamorTrade" : "GlamorTrade" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "GlamorTrade" %>">
  <meta name="author" content="GlamorTrade">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <% if admin_signed_in? %>
    <%= stylesheet_link_tag  'appui_amethyst', media: 'all', 'data-turbolinks-track' => true %>
  <% end %>

  <!-- Modernizr (browser feature detection library) -->
  <%= javascript_include_tag 'modernizr' %>

  <%= csrf_meta_tags %>

</head>
<body>

  <!-- Page Wrapper -->
  <div id="page-wrapper">
    <!-- Page Container -->
    <div id="page-container" class="header-fixed-top sidebar-visible-lg-full">

    <%= render "layouts/sidebar" %>

      <!-- Main Container -->
      <div id="main-container">
        <%= render "layouts/navigation" %>

      <!-- Page content -->
      <div id="page-content">

      <%= render "layouts/page_header" %>

          <%= render "layouts/messages" %>

          <%= yield %>

        </div>
        <!-- END Page Content -->
      </div>
      <!-- END Main Container -->
    </div>
    <!-- END Page Container -->
  </div>
  <!-- END Page Wrapper -->

</body>
</html>

app/views/layouts/devise.html.erb
</html><!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title><%= content_for?(:title) ? yield(:title) + " | GlamorTrade" : "GlamorTrade" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "GlamorTrade" %>">
  <meta name="author" content="GlamorTrade">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Modernizr (browser feature detection library) -->
  <%= javascript_include_tag 'modernizr' %>

  <%= csrf_meta_tags %>

</head>
<body>
  <!-- Login Container -->
  <div id="login-container">
    <!-- Login Header -->
    <h1 class="h2 text-light text-center push-top-bottom animation-slideDown">
      <i class="fa fa-cube"></i> Glamor<strong>Trade</strong>
    </h1>
    <!-- END Login Header -->

    <!-- Login Block -->
    <div class="block animation-fadeInQuickInv">
      <!-- Login Title -->
      <div class="block-title">
        <h2><%= yield(:title) %></h2>
      </div>
      <!-- END Login Title -->

      <%= render "layouts/messages" %>

      <%= yield %>

    </div>
    <!-- END Login Block -->

    <!-- Footer -->
    <footer class="text-muted text-center animation-pullUp">
      <%= render "devise/shared/links" %>
      <br />
      <small><span id="year-copy"></span> &copy; <%= link_to "Glamor<strong>Trade</strong>", root_path %></small>
    </footer>
    <!-- END Footer -->
  </div>
  <!-- END Login Container -->

</body>
</html>